#!/bin/sh
# Example of a meek-browser-helper program.
# This script creates a new profile, enables the meek-http-helper extension,
# and launches a new browser instance of it.

PROFILE="__meek-browser-helper"
PROFILEDIR="$HOME/.mozilla/firefox/__automated__.$PROFILE"
EXTID="meek-http-helper@bamsoftware.com"
EXTPATH="/usr/share/xul-ext/meek-http-helper"

set -e

firefox -CreateProfile "$PROFILE $PROFILEDIR" # nop if already exists
mkdir -p "$PROFILEDIR/extensions"
test -e "$PROFILEDIR/extensions/$EXTID" || ln -sf "$EXTPATH" "$PROFILEDIR/extensions/$EXTID"
test -f "$PROFILEDIR/extensions.ini" || cat >"$PROFILEDIR/extensions.ini" <<EOF
[ExtensionDirs]
Extension0=$PROFILEDIR/extensions/$EXTID
EOF

exec firefox -no-remote -P "$PROFILE"
